CREATE TABLE `MeetingJob` (
  `id` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NULL,
  `meetUrl` VARCHAR(191) NOT NULL,
  `meetCode` VARCHAR(191) NOT NULL,
  `status` ENUM(
    'QUEUED',
    'CLAIMED',
    'JOINING',
    'LIVE',
    'PROCESSING',
    'COMPLETED',
    'FAILED',
    'KICKED',
    'ENDED_EMPTY',
    'ENDED_ROOM_CLOSED'
  ) NOT NULL DEFAULT 'QUEUED',
  `endReason` ENUM(
    'HOST_NEVER_ADMITTED',
    'BOT_KICKED',
    'ROOM_ENDED',
    'LAST_PARTICIPANT_LEFT',
    'JOIN_TIMEOUT',
    'UNKNOWN'
  ) NULL,
  `workerId` VARCHAR(191) NULL,
  `errorMessage` TEXT NULL,
  `joinedAt` DATETIME(3) NULL,
  `startedAt` DATETIME(3) NULL,
  `endedAt` DATETIME(3) NULL,
  `recordingUrl` VARCHAR(191) NULL,
  `recordingKey` VARCHAR(191) NULL,
  `transcriptText` TEXT NULL,
  `transcriptJson` JSON NULL,
  `aiSummary` TEXT NULL,
  `participantsPeak` INTEGER NULL,
  `captionsEnabled` BOOLEAN NOT NULL DEFAULT false,
  `lastHeartbeatAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  INDEX `MeetingJob_status_createdAt_idx`(`status`, `createdAt`),
  INDEX `MeetingJob_meetCode_status_idx`(`meetCode`, `status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
